version: '3.8'
services:
  namenode:
    build:
      context: .
      dockerfile: ./namenode/Dockerfile
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    volumes:
      - namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"
    networks:
      - hadoop

  datanode:
    build:
      context: .
      dockerfile: ./datanode/Dockerfile
    container_name: datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - hadoop

  resourcemanager:
    build:
      context: .
      dockerfile: ./resourcemanager/Dockerfile
    container_name: resourcemanager
    environment:
      - YARN_RESOURCEMANAGER_HOSTNAME=resourcemanager
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "8088:8088"
    networks:
      - hadoop

  nodemanager:
    build:
      context: .
      dockerfile: ./nodemanager/Dockerfile
    container_name: nodemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    networks:
      - hadoop

volumes:
  namenode:
  datanode:

networks:
  hadoop:
