# ─────────────────────────────────────────────────────────────────────────────
# Dockerfile do DataNode
#
# Objetivo: 
#  - Basear em bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
#  - Não precisa de configurações adicionais, pois basta subir o DataNode
#  - O DataNode será configurado pelo docker-compose via variáveis de ambiente
# ─────────────────────────────────────────────────────────────────────────────

FROM bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
