# ─────────────────────────────────────────────────────────────────────────────
# Dockerfile do ResourceManager (YARN)
#
# Objetivo: 
#  - Basear em bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
#  - Não precisa de comandos extra; o entrypoint oficial subirá o RM
# ─────────────────────────────────────────────────────────────────────────────

FROM bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
